name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Replace Environment Variables
        run: |
          cd ./src/environments
          envsubst < environment.prod.ts > environment.prod-temp
          mv environment.prod-temp environment.prod.ts
          echo "environment.prod.ts"
          echo -n "$(cat environment.prod.ts )"
        shell: bash
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Build
        run: |
          echo -n "----------Where am i-----------"
          echo -n "$(pwd)"
          echo -n "environment.prod.ts"
          npm install
          npm run-script build:prod

      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/example-deploy
